groups:
  - name: Prometheus
    rules:
      - alert: Service down
        expr: up == 0
        for: 5m
        labels:
          level: critical
        annotations:
          labels: instance="{{ $labels.instance }}", job="{{ $labels.job }}"
