route:
  group_by: [ 'alertname' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'a2w'
receivers:
  - name: 'a2w'
    webhook_configs:
      - url: 'http://a2w:5001/send?key=<YOUR_KEY>'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: [ 'alertname', 'dev', 'instance' ]
